import Account from "../Screens/Home/User/Account";

export let strings={
    Allmost:'ALMOST THERE!',
    EnterMobileNo:'Please Enter Mobile No. Here',
    Mobile: 'Phone',
    Continue_Button:'CONTINUE',
    Login_Sign_Up:'Login / Signup',
    Fb_Token_Reject:'ERROR GETTING DATA FROM FACEBOOK',
    PhoneAlert:'Please enter phone no',
    PhoneValidError:'Please enter correct no',
    SelectDate:"Select Date",
    NextTime:"Next Avaliable Time",
    Verify:"Verify",
    ResendText1:"Didn't recieve the OTP?",
    ResendText2:"Resend OTP",
    AccountSetting:"Account Setting",
    ManageAccount:"Manage Profile",
    ManageGym:"Manage My Gym",
    WorkOutHistory:"WorkOut History",
    ManageUser:"Manage Users",
    ManageStaff:"Manage Staff",
    GetHelp:"Get Help",
    VerifyOtp:"Enter verification code",
    VerifyCode:"We have sent you a 4 digit verification code",
    Edit:"Edit",
    Delete:"Delete",
    DeleteSucess:"Deleted Succesfully",
    CreateAddon:"Create Addon",
    CreateWorkStationType:"Create Station Type",
    TodayGlance:"Today at a Glance",
    UpcomingAppoint:"UpComming Appointments",
    CompletedAppoint:"Completed Appointments",
    ExpectedRevenue:"Expected Revenue",
    NextAppoint:"Next Appointment",
    ActiveStation:"Most Active Station",

    // Upcoming:"UpComming",
    // Appointments:"Appointments",
    // Completed:"Completed",
    // Expected:"Expected",
    // Revenue:"Revenue",
    // Next:"Next",
    // MostActive:"Most Active",
    // Station:"Station",

    CreateStation:"Create Station",
    EditBooth:"Edit Station",
    CreateBooth:"Create Station",
    AvailabeAddOn:"Availabe Add Ons",
    SelectBoothType:"Select Station Type",
    BoothName:"Name Your Station",
    CancelledPicker:"User cancelled photo picker",
    ImagePickerError:"ImagePicker Error:",
    SelectPicture:"Please any select picture",
    EnterNameFirst:"Please Enter Name First",
    BoothTypeAlert:"Please select any  station type",
    SelectAddonsAlert:"Please any select addons",
    NoAddonAvailable:"No Addon Available",
    CreateShift:"Create Shift",
    SelectEndTime:"Select End Time",
    SelectStartTime:"Select Start Time",
    NoDataFound:"No Data Found",
    SelectShift:"Select Shift",
    GoBackToLogin: "Go Back To Login",
    Congratulations: "CONGRATULATIONS",
    ThankyouDesc:"You have successfully signed up with your number ",
    ThankyouDesc2:"Contact admin to activate your account.",
    Logout:'Logout',
}