export const GET_REPORT_SUCCESS = 'GET_REPORT_SUCCESS';
export const GET_REPORT_FAIL = 'GET_REPORT_FAIL';
export const GET_REPORT_MSG_READ = ' GET_REPORT_MSG_READ';
export const GET_LAB_REPORT_SUCCESS = 'GET_LAB_REPORT_SUCCESS';
export const GET_LAB_REPORT_FAIL = 'GET_LAB_REPORT_FAIL';
export const UPLOAD_REPORT_SUCCESS = 'UPLOAD_REPORT_SUCCESS';
export const UPLOAD_REPORT_FAIL = 'UPLOAD_REPORT_FAIL';
export const UPLOAD_REPORT_MSG_READ = 'UPLOAD_REPORT_MSG_READ';
export const OPEN_SHARE_REPORT = 'OPEN_SHARE_REPORT';
export const RESET_SHARE_REPORT = 'RESET_SHARE_REPORT';
export const SHARE_REPORT_SUCCESS = 'SHARE_REPORT_SUCCESS';
export const SHARE_REPORT_FAIL = 'SHARE_REPORT_FAIL';
export const SHARE_REPORT_MSG_READ = 'SHARE_REPORT_MSG_READ';
export const GET_USER_FAMILY_SUCCESS = 'GET_USER_FAMILY_SUCCESS';
export const GET_USER_FAMILY_FAIL = 'GET_USER_FAMILY_FAIL';
export const SELECT_REPORT_USER = 'SELECT_REPORT_USER';
export const RESET_REPORT_USER = 'RESET_REPORT_USER';
export const GET_REPORT = 'GET_REPORT';
export const GET_RECENT_RECORDS = 'GET_RECENT_RECORDS';
export const EDIT_REPORT_SUCCESS = 'EDIT_REPORT_SUCCESS';
export const EDIT_REPORT_FAIL = 'EDIT_REPORT_FAIL';
export const EDIT_REPORT_MSG_READ = 'EDIT_REPORT_MSG_READ';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const PROFILE_MSG_READ = 'PROFILE_MSG_READ';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAIL = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_MSG_READ = 'EDIT_PROFILE_MSG_READ';
export const UPDATE_REPORT_SUCCESS = 'UPDATE_REPORT_SUCCESS';
export const UPDATE_REPORT_FAIL = 'UPDATE_REPORT_FAIL';
export const UPDATE_REPORT_MSG_READ = 'UPDATE_REPORT_MSG_READ';
export const DELETE_REPORT_SUCCESS = 'DELETE_REPORT_SUCCESS';
export const DELETE_REPORT_FAIL = 'DELETE_REPORT_FAIL';
export const DELETE_REPORT_MSG_READ = 'DELETE_REPORT_MSG_READ';
export const PAYMENT_PLAN_SUCCESS = 'PAYMENT_PLAN_SUCCESS';
export const PAYMENT_PLAN_FAIL = 'PAYMENT_PLAN_FAIL';
export const PAYMENT_PLAN_RESET = 'PAYMENT_PLAN_RESET';

export const BILLING_URL = 'BILLING_URL';


export const LIST_PROFILE = 'LIST_PROFILE';
export const GET_LIST_PROFILE_FAIL = 'GET_LIST_PROFILE_FAIL';
export const GET_LIST_PROFILE_SUCCESS = 'GET_LIST_PROFILE_SUCCESS';


export const CONTACT_US_FAIL = 'CONTACT_US_FAIL';
export const CONTACT_US_SUCCESS = 'CONTACT_US_SUCCESS';
export const CONTACT_US_CHECKED = 'CONTACT_US_CHECKED';






